var PAT = "EAAfxssAeEOgBAIjIhjnCEZBQAVOc9SsKg2lFjqdI8aEH6sY9ZAapkPGlV2Kb8XeZCKVOCq7P9JgtXw9ZAvMbZC8SjNqGLHYHyuCOohOAsf2lTYCaSmZBDpIXKf8KJbff9VWdIPNN0I0dgUVE1mQUPupvYNVlC8IAev4uNKNZAgWXEtWEPUmYfmR"

module.exports = {
    PAGE_ACCESS_TOKEN: process.env.PAGE_ACCESS_TOKEN || PAT,
    VERIFICATION_TOKEN: process.env.VERIFICATION_TOKEN,
    FACEBOOK_GRAPH_API_BASE_URL: 'https://graph.facebook.com/v3.3/',
}
